-- Create Table
CREATE TABLE wellbeing_and_lifestyle (
 Timestamp DATE,
 FRUITS_VEGGIES INT,
 DAILY_STRESS VARCHAR,
 PLACES_VISTED INT,
 CORE_CIRCLE INT,
 SUPPORTING_OTHERS INT,
 SOCIAL_NETWORK INT,
 ACHIEVEMENT INT,
 DONATION INT,
 BMI_RANGE INT,
 TODO_COMPLETED INT,
 FLOW INT,
 DAILY_STEPS INT,
 LIVE_VISION INT,
 SLEEP_HOURS INT,
 LOST_VACATION INT,
 DAILY_SHOUTING INT,
 SUFFICIENT_INCOME INT,
 PERSONAL_AWARDS INT,
 TIME_FOR_PASSION INT,
 WEEKLY_MEDITATION INT,
 AGE TEXT,
 GENDER CHAR(6),
 WORK_LIFE_BALANCE_SCORE FLOAT(1)
);

-- odd input found in daily_stress