-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


SET XACT_ABORT ON

BEGIN TRANSACTION QUICKDBD

CREATE TABLE [wellbeing_and_lifestyle] (
    [Timestamp] DATE  NOT NULL ,
    [FRUITS_VEGGIES] INT  NOT NULL ,
    [DAILY_STRESS] INT  NOT NULL ,
    [PLACES_VISITED] INT  NOT NULL ,
    [CORE_CIRCLE] INT  NOT NULL ,
    [SUPPORTING_OTHERS] INT  NOT NULL ,
    [SOCIAL_NETWORK] INT  NOT NULL ,
    [ACHIEVEMENT] INT  NOT NULL ,
    [DONATION] INT  NOT NULL ,
    [BMI_RANGE] INT  NOT NULL ,
    [TODO_COMPLETED] INT  NOT NULL ,
    [FLOW] INT  NOT NULL ,
    [DAILY_STEPS] INT  NOT NULL ,
    [LIVE_VISION] INT  NOT NULL ,
    [SLEEP_HOURS] INT  NOT NULL ,
    [LOST_VACATION] INT  NOT NULL ,
    [DAILY_SHOUTING] INT  NOT NULL ,
    [SUFFICIENT_INCOME] INT  NOT NULL ,
    [PERSONAL_AWARDS] INT  NOT NULL ,
    [TIME_FOR_PASSION] INT  NOT NULL ,
    [WEEKLY_MEDITATION] INT  NOT NULL ,
    [AGE] TEXT  NOT NULL ,
    [GENDER] CHAR  NOT NULL ,
    [WORK_LIFE_BALANCE_SCORE] FLOAT  NOT NULL 
)

COMMIT TRANSACTION QUICKDBD